### ISSUE TITLE
Lib64 linux issue

### ISSUE THREAD

**Issue by mariolpantunes** [Ultimaker/Uranium#268]
Hi, in order to compile Cura (and all the libs) I had to patch up the CMakeLists.txt to correctly use Lib_Suffix.
I share my lib64.patch, if you found it acceptable can you add it to the code?
[lib64.txt](https://github.com/Ultimaker/Uranium/files/1156519/lib64.txt)

**Comment by Ghostkeeper** [comment]
Usually this is done via a pull request, but this would be okay too.

I can't open these attachments. Happened to me on different issues as well! I think there's some bug going on in Github or AWS because it's saying something about unsigned payloads :(

**Comment by Ghostkeeper** [comment]
Turns out that it was NoScript "fixing" the redirect because it was detecting an XSS attack due to Github using some unusual characters in their redirect.

So if I understood the code well, it basically only installs Uranium to the `dist-packages` directory if we're on Debian, but for other Linux distributions it still installs Uranium to the `site-packages` directory. Since `dist-packages` is a debian-only thing, this seems all right to me.

Just linking these issues together for posterity:
https://github.com/Ultimaker/libArcus/issues/61
https://github.com/Ultimaker/libSavitar/issues/5
https://github.com/Ultimaker/CuraEngine/issues/562
https://github.com/Ultimaker/Cura/issues/2134

**Comment by mariolpantunes** [comment]
Yes, that is the gist of things, my distribution also uses major.minor version for python folder (debian only uses major version).
Sorry for the delay replying.
I also added LIB_SUFFIX, since I read that was the CMAKE way to install libs in 64 bit linux.
However, colleague of mine pointed out that CMAKE_INSTALL_LIBDIR is the right way to do it.
I am in the process of testing his way.

These fixes will result in Cura package being available for Slackware linux.

**Comment by Ghostkeeper** [comment]
This should now be fixed: https://github.com/Ultimaker/Uranium/commit/10799d036710abc95956049252ccb6c98ea6ec3e

**Comment by mariolpantunes** [comment]
It is almost done.
Can you add support for libSuffix?
Instead of doing 
    install(DIRECTORY UM DESTINATION lib/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages)
just use
    install(DIRECTORY UM DESTINATION lib${LIB_SUFFIX}/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages)

**Comment by Ghostkeeper** [comment]
Ah yes, I thought I did that, but apparently not. Here you go:

https://github.com/Ultimaker/Cura/commit/aa92d4d0f97bcd36ccd1a7cfff30fd5fc68d843e
https://github.com/Ultimaker/Uranium/commit/862a246bdfd7e25541b04a35406957612c6f4bb7

**Comment by mariolpantunes** [comment]
Can you check if this works well with the plugins?
Another issue, can you add the same fix to the rest of lib (uranium, arcus, savitar and fdm_materials).

**Comment by Ghostkeeper** [comment]
It works on Ubuntu and Debian, but they have no suffix there. I have no computer available that has a suffix.

fdm_materials doesn't install to lib. Uranium is done in the link I posted above: https://github.com/Ultimaker/Uranium/commit/862a246bdfd7e25541b04a35406957612c6f4bb7. libArcus was already done here: https://github.com/Ultimaker/libArcus/commit/e6cb33bc528e1422f81ab0f7a24041168f4cd05b. libSavitar was already done here: https://github.com/Ultimaker/libSavitar/commit/aedac098bfd9a116aeaf46776cbcb67a902c77f9.
