### ISSUE TITLE
Poor performance of large lists such as Cura's print settings box under Linux

### ISSUE THREAD

**Issue by lf-** [Ultimaker/Uranium#379]
I've found Cura quite unpleasant to use because whenever either the program is started up or a search is cleared and all the items need to be displayed in the print settings list, it takes several seconds. I have reason to believe this is not a hardware performance issue as this occurs on a machine with a last-generation 45W mobile i7.

This is happening on Cura 3.4.1 from Arch Linux official repositories.

A video of the issue being reproduced is available at https://lfcode.ca/cura-slow-loading.mp4

**Comment by diegopradogesto** [comment]
We have some issues in the Cura repository indicating this and we are aware of it. Thanks for sharing this video, BTW.

However this is the Uranium repository that is only a dependency of Cura, but the main issue is caused by the huge amount of settings we need to manage in Cura and probably some other factors. Said that, I encourage you to either take a look to see if the issue was already reported or create a new one if not, but in the right repository.

**Comment by jackha** [comment]
We're going to investigate it a bit, but I will be hard.
CURA-5614
